### ISSUE TITLE
Write base R plot examples for each dataset

### ISSUE THREAD

**Issue by stephlocke** [lockedata/datasauRus#11]
These base R plot examples should be held in inst/examples and there should be one file per dataset

**Comment by maelle** [comment]
* And they should be added to the vignette

**Comment by maelle** [comment]
@stephlocke you mean the examples should be added to the bottom of the existing example files, right, not separately?

I'll let this issue open instead of fixing it and added a good first issue label.

**Comment by stephlocke** [comment]
Yeah - more working examples so folks can see what options they have

**Comment by starship9** [comment]
There are .R files present for every dataset (present in /data) already though, I'm confused. Which datasets need base plots?

**Comment by starship9** [comment]
Alright, so I use the .rda files present here (https://github.com/lockedata/datasauRus/tree/master/data) and just create new pull requests containing new base plots?

**Comment by starship9** [comment]
Is one file containing a for loop for multiple base plots acceptable?

**Comment by stephlocke** [comment]
@timbook did some great work on adding some plots @sgetalbo 

Do we need anymore plots Ellen or can we close the Issue?

**Comment by sgetalbo** [comment]
Hi both, these examples look great to me, thanks for getting involved Tim! 

datasauRus_dozen.R is without a base plot example - @timbook if you'd like to have a crack at that one too then consider it yours. I say leave the issue open for now - there's still a week to go after all, although could we update the ticket to reflect this comment perhaps? :)

**Comment by timbook** [comment]
Guess I missed one! I'm on it.
