### ISSUE TITLE
Update Box Plot Examples

### ISSUE THREAD

**Issue by jmatejka** [lockedata/datasauRus#18]
It seems I didn't have the right datafile for the box plot examples. I've created a new version (attached)

I'm not sure how to properly update the version in the package though...

[BoxPlots.txt](https://github.com/stephlocke/datasauRus/files/1222760/BoxPlots.txt)

**Comment by stephlocke** [comment]
Cheers Justin :D 

We'll get this new data incorporated - if you'd like to learn how we do it and work through it with me then https://calendly.com/lockedata/officehours

**Comment by jmatejka** [comment]
Thanks! (And for now at least, I've got enough languages on the go, I'll stay clear of R 😄)

**Comment by stephlocke** [comment]
I completely understand that sentiment! :)

**Comment by maelle** [comment]
Thanks @jmatejka, the package now features the updated box plot dataset.
