### ISSUE TITLE
Replace link to gif in the README

### ISSUE THREAD

**Issue by maelle** [lockedata/datasauRus#24]
Current link https://github.com/lockedata/lazyCDN/blob/master/DinoSequential.gif?raw=true

New link ?

**Comment by stephlocke** [comment]
If you could make a gif using gganimate or leverage one someone else has made and include in the README that'd be great!

**Comment by stephlocke** [comment]
and the link if you just wanna fix it should be https://github.com/stephlocke/lazyCDN/blob/master/DinoSequential.gif?raw=true

**Comment by maelle** [comment]
If we made a gif shouldn't it show the actual transitions, that we don't have, right? So we could re-do a gif using #14 

In the meantime I'll use the lazyCDN link.

**Comment by maelle** [comment]
I also need to fix its size because otherwise it looks bad in the pkgdown website. (using Markdown syntax)
